test

diff --git a/.github/tests.yml b/.github/tests.yml
--- a/.github/tests.yml
+++ b/.github/tests.yml
@@ -23,3 +23,10 @@ jobs:
 
     - name: Run Tests
       run: python -m unittest discover -s tests -p '*_test.py'
+
+    - name: Set Status
+      if: ${{ failure() }}
+      run: echo "Tests failed" && exit 1 || echo "Tests passed" && exit 0
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
